services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: entain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://root:root@postgres:5432/entain?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - migrate
    environment:
      ENTAIN_DB_DSN: postgres://root:root@postgres:5432/entain?sslmode=disable
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
